# -*- coding: utf-8 -*-
"""car_prices_cleaned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIIcvG8nN8cFF8Jj-f9-qOKXMmPbXkqC
"""

import pandas as pd
df = pd.read_csv('car_prices.csv')

df.isnull().sum()

fill_unknown = ['make', 'model', 'trim', 'body', 'transmission', 'color', 'interior', 'seller']
df[fill_unknown] = df[fill_unknown].fillna('unknown')

df.isnull().sum()

df['condition'] = df['condition'].fillna(df['condition'].median())
df['odometer'] = df['odometer'].fillna(df['odometer'].median())
df['mmr'] = df['mmr'].fillna(df['mmr'].median())
df['sellingprice'] = df['sellingprice'].fillna(df['sellingprice'].median())

df.isnull().sum()

df['state'] = df['state'].fillna(df['state'].mode()[0])
df['saledate'] = pd.to_datetime(df['saledate'], errors='coerce')
df['saledate'] = df['saledate'].fillna(method='ffill')

df.isnull().sum()

df.isnull().sum()

df.dropna(inplace=True)

print("✅ Missing values after cleaning:\n")
print(df.isnull().sum())

df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')

df.dtypes

df['saledate'] = pd.to_datetime(df['saledate'])

df['saledate'] = pd.to_datetime(df['saledate'], utc=True)

df.dtypes

df['saledate'] = df['saledate'].dt.tz_localize(None)

df.dtypes

df

df['saledate'] = pd.to_datetime(df['saledate'], utc=True).dt.tz_localize(None)

df

df['saledate'] = df['saledate'].dt.strftime('%d-%m-%Y')

df

df.drop_duplicates(inplace=True)

df[df.duplicated()]

